version: '3.8'

services:
  # PHP-FPM service for running Laravel application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"  # Expose port for Laravel server
    networks:
      - laravel

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3307:3306"  # Use a different port on host (3307 instead of 3306 to avoid conflict)

volumes:
  dbdata:
    driver: local

networks:
  laravel:
    driver: bridge
